In [1]:
import pandas as pd
from sqlalchemy import create_engine
import numpy as np

In [193]:
csv_file1 = "Resources/cfb20.csv"
cfb_data1 = pd.read_csv(csv_file1)
cfb_data1.head()

,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,Off.TDs,Off.Yards.per.Game,...,Average.Time.of.Possession.per.Game,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game
0,Air Force (Mountain West),6,3,3,73,373,2336,6.26,19,389.3,...,32:30,58,3,5,8,5,3,8,0,0.00
1,Akron (MAC),6,1,5,121,360,1687,4.69,12,281.2,...,30:35,98,4,2,6,3,6,9,-3,-0.50
2,Alabama (SEC),11,11,0,5,764,5983,7.83,68,543.9,...,30:45,12,10,11,21,7,4,11,10,0.91
3,App State (Sun Belt),12,9,3,26,845,5424,6.42,49,452.0,...,32:18,57,3,15,18,6,11,17,1,0.08
4,Arizona (Pac-12),5,0,5,86,373,1847,4.95,10,369.4,...,28:01,126,1,2,3,5,7,12,-9,-1.80

In [194]:
cfb_data1.insert(0, 'Year', '2020')

In [195]:
cfb_data1.insert(0, 'Unique_ID', range(0, 0 + len(cfb_data1)))

In [196]:
#cfb_data1 = cfb_data1.set_index('Unique_ID')

In [197]:
cfb_data1['Conference'] = (np.where(cfb_data1['Team'].str.contains(''),
                  cfb_data1['Team'].str.split('(').str[1],
                  cfb_data1['Team']))
cfb_data1.head()

,Unique_ID,Year,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,...,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game,Conference
0,0,2020,Air Force (Mountain West),6,3,3,73,373,2336,6.26,...,58,3,5,8,5,3,8,0,0.00,Mountain West)
1,1,2020,Akron (MAC),6,1,5,121,360,1687,4.69,...,98,4,2,6,3,6,9,-3,-0.50,MAC)
2,2,2020,Alabama (SEC),11,11,0,5,764,5983,7.83,...,12,10,11,21,7,4,11,10,0.91,SEC)
3,3,2020,App State (Sun Belt),12,9,3,26,845,5424,6.42,...,57,3,15,18,6,11,17,1,0.08,Sun Belt)
4,4,2020,Arizona (Pac-12),5,0,5,86,373,1847,4.95,...,126,1,2,3,5,7,12,-9,-1.80,Pac-12)

In [198]:
cfb_data1['Team'] = cfb_data1['Team'].str.split('(').str[0]
cfb_data1['Conference'] = cfb_data1['Conference'].str.split(')').str[0]
cfb_data1.head()

,Unique_ID,Year,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,...,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game,Conference
0,0,2020,Air Force,6,3,3,73,373,2336,6.26,...,58,3,5,8,5,3,8,0,0.00,Mountain West
1,1,2020,Akron,6,1,5,121,360,1687,4.69,...,98,4,2,6,3,6,9,-3,-0.50,MAC
2,2,2020,Alabama,11,11,0,5,764,5983,7.83,...,12,10,11,21,7,4,11,10,0.91,SEC
3,3,2020,App State,12,9,3,26,845,5424,6.42,...,57,3,15,18,6,11,17,1,0.08,Sun Belt
4,4,2020,Arizona,5,0,5,86,373,1847,4.95,...,126,1,2,3,5,7,12,-9,-1.80,Pac-12

In [199]:
cfb_data1.head()

,Unique_ID,Year,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,...,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game,Conference
0,0,2020,Air Force,6,3,3,73,373,2336,6.26,...,58,3,5,8,5,3,8,0,0.00,Mountain West
1,1,2020,Akron,6,1,5,121,360,1687,4.69,...,98,4,2,6,3,6,9,-3,-0.50,MAC
2,2,2020,Alabama,11,11,0,5,764,5983,7.83,...,12,10,11,21,7,4,11,10,0.91,SEC
3,3,2020,App State,12,9,3,26,845,5424,6.42,...,57,3,15,18,6,11,17,1,0.08,Sun Belt
4,4,2020,Arizona,5,0,5,86,373,1847,4.95,...,126,1,2,3,5,7,12,-9,-1.80,Pac-12

In [200]:
csv_file2 = "Resources/cfb19.csv"
cfb_data2 = pd.read_csv(csv_file2)
cfb_data2.head()

,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,Off.TDs,Off.Yards.per.Game,...,Average.Time.of.Possession.per.Game,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game
0,Air Force (Mountain West),13,11,2,51,881,5483,6.22,55,421.8,...,34:28,78,9,7,16,12,6,18,-2,-0.15
1,Akron (MAC),12,0,12,130,725,2918,4.02,14,243.2,...,26:29,128,6,5,11,12,14,26,-15,-1.25
2,Alabama (SEC),13,11,2,6,842,6640,7.89,76,510.8,...,29:59,3,11,17,28,4,6,10,18,1.38
3,Appalachian St. (Sun Belt),14,13,1,39,969,6064,6.26,65,433.1,...,31:19,7,10,14,24,3,6,9,15,1.07
4,Arizona (Pac-12),12,4,8,30,873,5281,6.05,42,440.1,...,27:24,89,4,11,15,6,12,18,-3,-0.25

In [201]:
cfb_data2.insert(0, 'Year', '2019')

In [202]:
cfb_data2.insert(0, 'Unique_ID', range(0, 0 + len(cfb_data2)))

In [203]:
#cfb_data2 = cfb_data2.set_index('Unique_ID')

In [204]:
cfb_data2['Conference'] = (np.where(cfb_data2['Team'].str.contains(''),
                  cfb_data2['Team'].str.split('(').str[1],
                  cfb_data2['Team']))
cfb_data2.head()

,Unique_ID,Year,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,...,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game,Conference
0,0,2019,Air Force (Mountain West),13,11,2,51,881,5483,6.22,...,78,9,7,16,12,6,18,-2,-0.15,Mountain West)
1,1,2019,Akron (MAC),12,0,12,130,725,2918,4.02,...,128,6,5,11,12,14,26,-15,-1.25,MAC)
2,2,2019,Alabama (SEC),13,11,2,6,842,6640,7.89,...,3,11,17,28,4,6,10,18,1.38,SEC)
3,3,2019,Appalachian St. (Sun Belt),14,13,1,39,969,6064,6.26,...,7,10,14,24,3,6,9,15,1.07,Sun Belt)
4,4,2019,Arizona (Pac-12),12,4,8,30,873,5281,6.05,...,89,4,11,15,6,12,18,-3,-0.25,Pac-12)

In [205]:
cfb_data2['Team'] = cfb_data2['Team'].str.split('(').str[0]
cfb_data2['Conference'] = cfb_data2['Conference'].str.split(')').str[0]

In [206]:
cfb_data2.head()

,Unique_ID,Year,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,...,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game,Conference
0,0,2019,Air Force,13,11,2,51,881,5483,6.22,...,78,9,7,16,12,6,18,-2,-0.15,Mountain West
1,1,2019,Akron,12,0,12,130,725,2918,4.02,...,128,6,5,11,12,14,26,-15,-1.25,MAC
2,2,2019,Alabama,13,11,2,6,842,6640,7.89,...,3,11,17,28,4,6,10,18,1.38,SEC
3,3,2019,Appalachian St.,14,13,1,39,969,6064,6.26,...,7,10,14,24,3,6,9,15,1.07,Sun Belt
4,4,2019,Arizona,12,4,8,30,873,5281,6.05,...,89,4,11,15,6,12,18,-3,-0.25,Pac-12

In [207]:
csv_file3 = "Resources/cfb18.csv"
cfb_data3 = pd.read_csv(csv_file3)
cfb_data3

,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,Off.TDs,Off.Yards.per.Game,...,Average.Time.of.Possession.per.Game,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game
0,Air Force (MWC),12,5,7,52,882,4978,5.64,43,414.8,...,34:22,77,7,7,14,10,5,15,-1,-0.08
1,Akron (MAC),12,4,8,126,764,3533,4.62,21,294.4,...,28:09,103,11,10,21,12,14,26,-5,-0.42
2,Alabama (SEC),15,14,1,6,1009,7830,7.76,85,522.0,...,30:19,34,7,14,21,7,8,15,6,0.40
3,Appalachian St. (Sun Belt),13,11,2,37,859,5603,6.52,58,431.0,...,30:34,30,6,17,23,5,12,17,6,0.46
4,Arizona (Pac-12),12,5,7,24,881,5492,6.23,43,457.7,...,28:15,90,8,7,15,9,10,19,-4,-0.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,West Virginia (Big 12),12,8,4,8,870,6147,7.07,60,512.3,...,28:50,23,9,15,24,7,10,17,7,0.58
125,Western Ky. (C-USA),12,3,9,101,870,4364,5.02,30,363.7,...,29:23,52,6,12,18,6,10,16,2,0.17
126,Western Mich. (MAC),13,7,6,35,962,5679,5.90,52,436.8,...,33:36,63,11,9,20,10,9,19,1,0.08
127,Wisconsin (Big Ten),13,8,5,36,875,5604,6.40,51,431.1,...,32:04,63,11,14,25,10,14,24,1,0.08
128,Wyoming (MWC),12,6,6,118,771,3969,5.15,27,330.8,...,29:56,40,5,10,15,7,4,11,4,0.33

In [208]:
cfb_data3.insert(0, 'Year', '2018')

In [209]:
cfb_data3.insert(0, 'Unique_ID', range(0, 0 + len(cfb_data3)))

In [210]:
#cfb_data3 = cfb_data3.set_index('Unique_ID')

In [211]:
cfb_data3['Conference'] = (np.where(cfb_data3['Team'].str.contains(''),
                  cfb_data3['Team'].str.split('(').str[1],
                  cfb_data3['Team']))

In [212]:
cfb_data3['Team'] = cfb_data3['Team'].str.split('(').str[0]
cfb_data3['Conference'] = cfb_data3['Conference'].str.split(')').str[0]

In [213]:
cfb_data3.head()

,Unique_ID,Year,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,...,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game,Conference
0,0,2018,Air Force,12,5,7,52,882,4978,5.64,...,77,7,7,14,10,5,15,-1,-0.08,MWC
1,1,2018,Akron,12,4,8,126,764,3533,4.62,...,103,11,10,21,12,14,26,-5,-0.42,MAC
2,2,2018,Alabama,15,14,1,6,1009,7830,7.76,...,34,7,14,21,7,8,15,6,0.40,SEC
3,3,2018,Appalachian St.,13,11,2,37,859,5603,6.52,...,30,6,17,23,5,12,17,6,0.46,Sun Belt
4,4,2018,Arizona,12,5,7,24,881,5492,6.23,...,90,8,7,15,9,10,19,-4,-0.33,Pac-12

In [214]:
partial_append_df = cfb_data2.append(cfb_data3)

In [215]:
final_df = cfb_data1.append(partial_append_df)

In [216]:
final_df

,Unique_ID,Year,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,...,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game,Conference
0,0,2020,Air Force,6,3,3,73,373,2336,6.26,...,58,3,5,8,5,3,8,0,0.00,Mountain West
1,1,2020,Akron,6,1,5,121,360,1687,4.69,...,98,4,2,6,3,6,9,-3,-0.50,MAC
2,2,2020,Alabama,11,11,0,5,764,5983,7.83,...,12,10,11,21,7,4,11,10,0.91,SEC
3,3,2020,App State,12,9,3,26,845,5424,6.42,...,57,3,15,18,6,11,17,1,0.08,Sun Belt
4,4,2020,Arizona,5,0,5,86,373,1847,4.95,...,126,1,2,3,5,7,12,-9,-1.80,Pac-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,124,2018,West Virginia,12,8,4,8,870,6147,7.07,...,23,9,15,24,7,10,17,7,0.58,Big 12
125,125,2018,Western Ky.,12,3,9,101,870,4364,5.02,...,52,6,12,18,6,10,16,2,0.17,C-USA
126,126,2018,Western Mich.,13,7,6,35,962,5679,5.90,...,63,11,9,20,10,9,19,1,0.08,MAC
127,127,2018,Wisconsin,13,8,5,36,875,5604,6.40,...,63,11,14,25,10,14,24,1,0.08,Big Ten
128,128,2018,Wyoming,12,6,6,118,771,3969,5.15,...,40,5,10,15,7,4,11,4,0.33,MWC

In [217]:
#final_df.insert(0, 'Unique_ID', range(0, 0 + len(final_df)))

In [218]:
#final_df = final_df.set_index('Unique_ID')

In [219]:
final_df['Team'] = final_df['Team'].str.strip()
final_df['Conference'] = final_df['Conference'].str.strip()

In [220]:
final_df

,Unique_ID,Year,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,...,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game,Conference
0,0,2020,Air Force,6,3,3,73,373,2336,6.26,...,58,3,5,8,5,3,8,0,0.00,Mountain West
1,1,2020,Akron,6,1,5,121,360,1687,4.69,...,98,4,2,6,3,6,9,-3,-0.50,MAC
2,2,2020,Alabama,11,11,0,5,764,5983,7.83,...,12,10,11,21,7,4,11,10,0.91,SEC
3,3,2020,App State,12,9,3,26,845,5424,6.42,...,57,3,15,18,6,11,17,1,0.08,Sun Belt
4,4,2020,Arizona,5,0,5,86,373,1847,4.95,...,126,1,2,3,5,7,12,-9,-1.80,Pac-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,124,2018,West Virginia,12,8,4,8,870,6147,7.07,...,23,9,15,24,7,10,17,7,0.58,Big 12
125,125,2018,Western Ky.,12,3,9,101,870,4364,5.02,...,52,6,12,18,6,10,16,2,0.17,C-USA
126,126,2018,Western Mich.,13,7,6,35,962,5679,5.90,...,63,11,9,20,10,9,19,1,0.08,MAC
127,127,2018,Wisconsin,13,8,5,36,875,5604,6.40,...,63,11,14,25,10,14,24,1,0.08,Big Ten
128,128,2018,Wyoming,12,6,6,118,771,3969,5.15,...,40,5,10,15,7,4,11,4,0.33,MWC

In [221]:
final_df.loc[final_df['Team'] == 'Alabama']

,Unique_ID,Year,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,...,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game,Conference
2,2,2020,Alabama,11,11,0,5,764,5983,7.83,...,12,10,11,21,7,4,11,10,0.91,SEC
2,2,2019,Alabama,13,11,2,6,842,6640,7.89,...,3,11,17,28,4,6,10,18,1.38,SEC
2,2,2018,Alabama,15,14,1,6,1009,7830,7.76,...,34,7,14,21,7,8,15,6,0.40,SEC

In [222]:
final_df.columns = final_df.columns.str.replace('.', '_')

<ipython-input-222-aa8c013ec172>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  final_df.columns = final_df.columns.str.replace('.', '_')

In [223]:
final_df

,Unique_ID,Year,Team,Games,Win,Loss,Off_Rank,Off_Plays,Off_Yards,Off_Yards_Play,...,Turnover_Rank,Fumbles_Recovered,Opponents_Intercepted,Turnovers_Gain,Fumbles_Lost,Interceptions_Thrown_y,Turnovers_Lost,Turnover_Margin,Avg_Turnover_Margin_per_Game,Conference
0,0,2020,Air Force,6,3,3,73,373,2336,6.26,...,58,3,5,8,5,3,8,0,0.00,Mountain West
1,1,2020,Akron,6,1,5,121,360,1687,4.69,...,98,4,2,6,3,6,9,-3,-0.50,MAC
2,2,2020,Alabama,11,11,0,5,764,5983,7.83,...,12,10,11,21,7,4,11,10,0.91,SEC
3,3,2020,App State,12,9,3,26,845,5424,6.42,...,57,3,15,18,6,11,17,1,0.08,Sun Belt
4,4,2020,Arizona,5,0,5,86,373,1847,4.95,...,126,1,2,3,5,7,12,-9,-1.80,Pac-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,124,2018,West Virginia,12,8,4,8,870,6147,7.07,...,23,9,15,24,7,10,17,7,0.58,Big 12
125,125,2018,Western Ky.,12,3,9,101,870,4364,5.02,...,52,6,12,18,6,10,16,2,0.17,C-USA
126,126,2018,Western Mich.,13,7,6,35,962,5679,5.90,...,63,11,9,20,10,9,19,1,0.08,MAC
127,127,2018,Wisconsin,13,8,5,36,875,5604,6.40,...,63,11,14,25,10,14,24,1,0.08,Big Ten
128,128,2018,Wyoming,12,6,6,118,771,3969,5.15,...,40,5,10,15,7,4,11,4,0.33,MWC

In [224]:
columns = final_df.columns.values.tolist()
columns

['Unique_ID',
 'Year',
 'Team',
 'Games',
 'Win',
 'Loss',
 'Off_Rank',
 'Off_Plays',
 'Off_Yards',
 'Off_Yards_Play',
 'Off_TDs',
 'Off_Yards_per_Game',
 'Def_Rank',
 'Def_Plays',
 'Yards_Allowed',
 'Yards_Play_Allowed',
 'Off_TDs_Allowed',
 'Total_TDs_Allowed',
 'Yards_Per_Game_Allowed',
 'First_Down_Rank',
 'First_Down_Runs',
 'First_Down_Passes',
 'First_Down_Penalties',
 'First_Downs',
 'First_Down_Def_Rank',
 'Opp_First_Down_Runs',
 'Opp_First_Down_Passes',
 'Opp_First_Down_Penalties',
 'Opp_First_Downs',
 'X4th_Down_Rank',
 'X4th_Attempts',
 'X4th_Conversions',
 'X4th_Percent',
 'X4rd_Down_Def_Rank',
 'Opp_4th_Conversion',
 'Opp_4th_Attempt',
 'Opponent_4th_Percent',
 'Kickoff_Return_Rank',
 'Kickoffs_Returned',
 'Kickoff_Return_Yards',
 'Kickoff_Return_Touchdowns',
 'Avg_Yard_per_Kickoff_Return',
 '___40',
 'Kickoff_Return_Def_Rank',
 'Opp_Kickoff_Returns',
 'Kickoff_Touchbacks',
 'Opponent_Kickoff_Return_Yards',
 'Opp_Kickoff_Return_Touchdowns_Allowed',
 'Avg_Yards_per_Kickoff_Return_Allowed',
 'Passing_Off_Rank',
 'Pass_Attempts',
 'Pass_Completions',
 'Interceptions_Thrown_x',
 'Pass_Yards',
 'Pass_Yards_Attempt',
 'Yards_Completion',
 'Pass_Touchdowns',
 'Pass_Yards_Per_Game',
 'Pass_Def_Rank',
 'Opp_Completions_Allowed',
 'Opp_Pass_Attempts',
 'Opp_Pass_Yds_Allowed',
 'Opp_Pass_TDs_Allowed',
 'Yards_Attempt_Allowed',
 'Yards_Completion_Allowed',
 'Pass_Yards_Per_Game_Allowed',
 'Penalty_Rank',
 'Penalties',
 'Penalty_Yards',
 'Penalty_Yards_Per_Game',
 'Punt_Return_Rank',
 'Punt_Returns',
 'Net_Punt_Return_Yards',
 'Punt_Return_Touchdowns',
 'Avg_Yards_Per_Punt_Return',
 'Punt_Return_Def_Rank',
 'Opp_Punt_Returns',
 'Opp_Net_Punt_Return_Yards',
 'Opp_Punt_Return_Touchdowns_Allowed',
 'Avg_Yards_Allowed_per_Punt_Return',
 'Redzone_Off_Rank',
 'Redzone_Attempts',
 'Redzone_Rush_TD',
 'Redzone_Pass_TD',
 'Redzone_Field_Goals_Made',
 'Redzone_Scores',
 'Redzone_Points',
 'Redzone_Def_Rank',
 'Opp_Redzone_Attempts',
 'Opp_Redzone_Rush_TD_Allowed',
 'Opp_Redzone_Pass_Touchdowns_Allowed',
 'Opp_Redzone_Field_Goals_Made',
 'Opp_Redzone_Scores',
 'Redzone_Points_Allowed',
 'Rushing_Off_Rank',
 'Rush_Attempts',
 'Rush_Yds',
 'Yards_Rush',
 'Rushing_TD',
 'Rushing_Yards_per_Game',
 'Rushing_Def_Rank',
 'Opp_Rush_Attempts',
 'Opp_Rush_Yards_Alloweed',
 'Yds_Rush_Allowed',
 'Opp_Rush_Touchdowns_Allowed',
 'Rush_Yards_Per_Game_Allowed',
 'Sack_Rank',
 'Sacks',
 'Sack_Yards',
 'Average_Sacks_per_Game',
 'Scoring_Def_Rank',
 'Touchdowns_Allowed',
 'Opponent_Extra_Points',
 'X2_Point_Conversions_Allowed',
 'Opp_Deflected_Extra_Points',
 'Opp_Feild_Goals_Made',
 'Opp_Safety',
 'Points_Allowed',
 'Avg_Points_per_Game_Allowed',
 'Scoring_Off_Rank',
 'Touchdowns',
 'PAT',
 'X2_Point_Conversions',
 'Defensive_Points',
 'Feild_Goals',
 'Safety',
 'Total_Points',
 'Points_Per_Game',
 'Tackle_for_Loss_Rank',
 'Solo_Tackle_For_Loss',
 'Assist_Tackle_For_Loss',
 'Tackle_for_Loss_Yards',
 'Total_Tackle_For_Loss',
 'Tackle_For_Loss_Per_Game',
 'X3rd_Down_Rank',
 'X3rd_Attempts',
 'X3rd_Conversions',
 'X3rd_Percent',
 'X3rd_Down_Def_Rank',
 'Opp_3rd_Conversion',
 'Opp_3rd_Attempt',
 'Opponent_3rd_Percent',
 'Time_of_Possession_Rank',
 'Time_of_Possession',
 'Average_Time_of_Possession_per_Game',
 'Turnover_Rank',
 'Fumbles_Recovered',
 'Opponents_Intercepted',
 'Turnovers_Gain',
 'Fumbles_Lost',
 'Interceptions_Thrown_y',
 'Turnovers_Lost',
 'Turnover_Margin',
 'Avg_Turnover_Margin_per_Game',
 'Conference']

In [230]:
win_loss = final_df[["Unique_ID", "Team", "Games", "Win", "Loss"]]
win_loss.set_index("Unique_ID", inplace=True)
win_loss

                    Team  Games  Win  Loss
Unique_ID
0              Air Force      6    3     3
1                  Akron      6    1     5
2                Alabama     11   11     0
3              App State     12    9     3
4                Arizona      5    0     5
...                  ...    ...  ...   ...
124        West Virginia     12    8     4
125          Western Ky.     12    3     9
126        Western Mich.     13    7     6
127            Wisconsin     13    8     5
128              Wyoming     12    6     6

[386 rows x 4 columns]

In [26]:
new_cfb_data1 = cfb_data1[['Team', 'Games', 'Win', 'Loss']].copy()
new_cfb_data1.head()

         Team  Games  Win  Loss
0  Air Force       6    3     3
1      Akron       6    1     5
2    Alabama      11   11     0
3  App State      12    9     3
4    Arizona       5    0     5

In [27]:
rds_connection_string = "postgres:Speaker34j!@localhost:5432/college_football"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [28]:
engine.table_names()

['team_name']

In [29]:
new_cfb_data1.to_sql(name='team_name', con=engine, if_exists='append', index=False)

In [30]:
pd.read_sql_query('select * from team_name', con=engine)

               Team  Games  Win  Loss
0        Air Force       6    3     3
1            Akron       6    1     5
2          Alabama      11   11     0
3        App State      12    9     3
4          Arizona       5    0     5
..              ...    ...  ...   ...
249  West Virginia       9    5     4
250    Western Ky.      11    5     6
251  Western Mich.       6    4     2
252      Wisconsin       6    3     3
253        Wyoming       6    2     4

[254 rows x 4 columns]